### ISSUE TITLE
request shell account

### ISSUE THREAD

**Issue by solidboy** [tokyoshells/issues#12]
Preferred username: solidboy
Email address: marchel.solidboy@gmail.com
IRC Nickname: solidboy

this shell for tunneling activity.... thanks

**Comment by an-empty-string** [comment]
Please state the reason you are requesting an account.

**Comment by solidboy** [comment]
ok..

**Comment by solidboy** [comment]
admin... accept my request??

**Comment by an-empty-string** [comment]
Be patient please, I'll create your account later today.

**Comment by solidboy** [comment]
ok..

**Comment by an-empty-string** [comment]
Declined.
