### ISSUE TITLE
Account Request

### ISSUE THREAD

**Issue by Agent-Isai** [tokyoshells/issues#17]
<b> Preferred Username:</b> Isai
<b> Email Address:</b> isaicastro99@yahoo.com
<b> IRC Nick:</b> Agent_Isai
I want a tokyoshell because I need SSH Access to do stuff, I also saw you offered an IRC Bot Service and I'd like an IRC bot and I also saw you offered web hosting, I need a good reliable web hosting service for my website.

**Comment by an-empty-string** [comment]
Pretty sure I set you up over IRC, ping me if I didn't.
