### ISSUE TITLE
Account request: xnrand

### ISSUE THREAD

**Issue by thegrumble** [tokyoshells/issues#18]
**Preferred username**: `xnrand`
**Email address**: `xnrand [ᴀᴛ] openmailbox [ᴅᴏᴛ] org`
**IRC Nickname** (freenode): `xnrand`
I would like to use a tokyoshells account for testing a software which I am writing that relies on server/server and server/client communications on diverse environments and for running a text-based IRC client so I have a place to properly chat from in case the server that I am mainly using for IRC goes down.

**Comment by an-empty-string** [comment]
Done
