### ISSUE TITLE
Account request

### ISSUE THREAD

**Issue by SuperMiron** [tokyoshells/issues#25]
Preferred username: supermiron
Email address: mironstuff@myself.com
I will be using tokyoshells for ZNC and possibly an IRC bot.

**Comment by an-empty-string** [comment]
I should probably know this, but what's your freenode IRC nickname?

**Comment by SuperMiron** [comment]
Miron

**Comment by SuperMiron** [comment]
I apologize for my impatience, but it's been over 2 weeks...

**Comment by an-empty-string** [comment]
No, don't worry about it, that's my fault. Can you ping me (fwilson) on IRC
later today (ideally between 11:45 and 12:30 EST, but any time works), and
I can get you set up.

**Comment by an-empty-string** [comment]
Check your IRC PMs
