### ISSUE TITLE
Account Disabled?

### ISSUE THREAD

**Issue by Agent-Isai** [tokyoshells/issues#31]
I was trying to login to shells but I got this:

Connecting to tokyoshells.cf:22 via ssh 
Connection Lost
recvfrom failed: ECONNRESET (Connection reset by peer)

Usally that means the account doesn't exist, therefor it disconnects me. If my account got deleted, please tell me why. Thanks!

**Comment by an-empty-string** [comment]
Denyhosts probably didn't like you, can you PM me on IRC?

**Comment by an-empty-string** [comment]
Fixed over IRC

**Comment by Agent-Isai** [comment]
Now I can't sFTP in :/
