### ISSUE TITLE
firewall / open port

### ISSUE THREAD

**Issue by freeshell** [tokyoshells/issues#33]
hi, its kingkong. installed znc and my znc user can connect to irc. but i can not connect to znc. is there firewall or another problem? if so, can you open port for me, please? on irc fwilson said thats firewall problem. so, how to fix this?

**Comment by an-empty-string** [comment]
What port are you using?

**Comment by freeshell** [comment]
i was testing on one bot to link with my znc on port 64613. and i will link other my bots at 64614 and 64615 ports with znc too. can you assing those ports on my account please. thanks in advance.

**Comment by an-empty-string** [comment]
Done
