### ISSUE TITLE
Hosting a webpage in public_html directory

### ISSUE THREAD

**Issue by brrr2** [tokyoshells/issues#37]
Is it still possible to host a webpage through the public_html directory? If so, what file permissions should the directory have?

**Comment by an-empty-string** [comment]
Yes -- I haven't yet configured Apache for this though.

**Comment by an-empty-string** [comment]
_wheeeeee apache configuration_

**Comment by an-empty-string** [comment]
s/apache/nginx/

**Comment by an-empty-string** [comment]
Okay, you need to set o+rx on public_html and o+x on your home directory. That should work ( see for example http://tokyoshells.cf/~fwilson/ )

**Comment by brrr2** [comment]
Thanks!
