### ISSUE TITLE
Replace denyhosts with fail2ban

### ISSUE THREAD

**Issue by an-empty-string** [tokyoshells/issues#39]
Denyhosts has a nasty habit of banning random users whenever it feels like it. This should be fixed.

**Comment by an-empty-string** [comment]
@sckasturi do you have the time to do this? I'm a little busy at the moment

**Comment by sckasturi** [comment]
@fwilson42 yeah sure, I can do this in a bit.

–Srijay Kasturi
http://techfilmer.com

**Comment by sckasturi** [comment]
done!
