### ISSUE TITLE
Package request sqlite

### ISSUE THREAD

**Issue by Tweetvito** [tokyoshells/issues#48]
Package : sqlite
Version : current
Package name (debian) : sqlite 

Thanks :)

**Comment by an-empty-string** [comment]
sqlite3 is already installed, do you need an earlier version or will that do?

**Comment by Tweetvito** [comment]
sqlite3 is installed , sqlite no ... is a different package

**Comment by an-empty-string** [comment]
Will you be able to configure your application to use sqlite3 instead, though? I'd prefer to only have one version at a time (although if it's really necessary I can install it)

**Comment by Tweetvito** [comment]
i want load on supybot 'encyclopedia' plugin and the error is : Error: No module named sqlite

**Comment by an-empty-string** [comment]
Okay, I've installed the python-sqlite package, which should do what you need. Feel free to reopen this issue if you have any problems.

**Comment by Tweetvito** [comment]
Also the package python-tz
