### ISSUE TITLE
Username change Request

### ISSUE THREAD

**Issue by RazorCoding** [tokyoshells/issues#57]
i would like to change my username, to bushido
one more thing i need the installation of twitter api, "https://pypi.python.org/pypi/twitter"

**Comment by sckasturi** [comment]
What is your current username?

–Srijay Kasturi
http://techfilmer.com

**Comment by RazorCoding** [comment]
my current username= bursihido

**Comment by RazorCoding** [comment]
i did still get my username changed?

**Comment by sckasturi** [comment]
sorry for the delay, but both are done!
