### ISSUE TITLE
Package requests

### ISSUE THREAD

**Issue by Agent-Isai** [tokyoshells/issues#58]
<b>Package(s):</b> python3-oauth2 and python twitter 
<b>Version</b>: (Whatever version Debian  gives)
<b>Package(s) name(s):</b>python3-oauth2 and python3-twitter

**Comment by sckasturi** [comment]
```
skasturi@tokyo  $ sudo apt-get install python3-oauth2 python3-twitter
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python3-oauth2
E: Unable to locate package python3-twitter
```

could you link me to the packages?

**Comment by Agent-Isai** [comment]
Oh, python3-oauth2 is only available for the new stable (Jessie) and I believe doing "pip3 install twitter" (as root) will install python3-twitter

**Comment by cydrobolt** [comment]
Can you run it in a Python `virtualenv`?

**Comment by sckasturi** [comment]
Closing as nothing has really happened and I'm guessing you don't need this package anymore.
