### ISSUE TITLE
Request to open 4 ports.

### ISSUE THREAD

**Issue by nolsen42** [tokyoshells/issues#66]
My ports are encrypted with PGP so some script kiddy doesn't see them.

-----BEGIN PGP MESSAGE-----
Version: BCPG C# v1.6.1.0

hQEMA6HTJI07EIXCAQgAnCJQt4cAaZ3UQChlma2+Gce+HtV2npGF1lZPtqvMX43J
Qu0oJLswvH8pXbYUH7NJAWdDtx2oKiiz4bJpRyIig9V6IAM/2S3+jk/iq5Ts10eo
vtFjcq2ukQeZDXMnkOdYAPKRh2FkGyyWMxUPyPHip8ojK8rrEOqcf1CBSkn7L3yJ
LO7MN2ffh/EFVGQq4+Hr3EOmG0lXihIxJnc9kAcVVsDeaBQGK4seOkQdOTPG17E9
R93vKpgqD/WnHxKFDNq4+mA+RAMiDa/LVB4FLJZOYbqdFfMw8CE+dO4yifU1xzbN
GilClIaAY4PUbIrZcuphZDOGirKIlK2OS0A1cu4cbsm7TfJkvZwD1eIQuDeJM+2e
PbmKxsoBSO78EwBoLilXutYPG0a+TO5adD1ovUyzJenAWhgMtfzaoEhrQhYIwtD9
LHy16c1YoxD2PKDgjCKCLbMaQfAWOQvqXLqXh4EtyU+OxFmMbCLiB91d7tQE381Q
GFjb6cJeWdY9L6ZncVJQjV/muS5gnN34azps6PfqzOyG1IB0Ff/rQ9AiCJIifGlT
M/wcSCvEEtshOtyysKR2AVKp2t/LfMb+SgF0ZQ==
=j29h
-----END PGP MESSAGE-----

PM me on IRC for the Private Key to decode this.

**Comment by sckasturi** [comment]
Please provide us with the unencrypted version. For the sake of
transparency, and logging, this must be done on Github, and through
cleartext.

**Comment by nolsen42** [comment]
The Ports are 9987, 10011, 30033, and 5000

Ports 9987, 10011, 30033 will be used for TS3 since those are the default TS3 ports.

Port 5000 is used to create a telnet-based server I'm going to create for project v-Dialup.

**Comment by nolsen42** [comment]
_sigh_ I guess I have to put a password on the TS3 server or just ban people who enters it unauthorized.
