### ISSUE TITLE
Requesting removal of account

### ISSUE THREAD

**Issue by vijaiaeroastro** [tokyoshells/issues#9]
I request y'all to remove my shell account with the username "vijai". I thank y'all very much for the shell. I learned a lot from it. Now i can't seem to login regularly so i figured it should be useful to some one else. So i kindly request you to delete my shell account.

**Comment by an-empty-string** [comment]
Sorry this is so late -- do you mind logging in and creating a file called "delete-account-request" in your home directory?

**Comment by vijaiaeroastro** [comment]
Done @fwilson42

**Comment by an-empty-string** [comment]
Account deleted. Feel free to reopen this issue if you ever need or want it back.
